---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	initialize(initialize)
	planner(planner)
	strategy_select(strategy_select)
	retrieve(retrieve)
	evaluate_context(evaluate_context)
	decide_next_action(decide_next_action)
	apply_retry(apply_retry)
	generate_answer(generate_answer)
	build_insufficient_evidence(build_insufficient_evidence)
	finalize_trace(finalize_trace)
	__end__([<p>__end__</p>]):::last
	__start__ --> initialize;
	apply_retry --> retrieve;
	build_insufficient_evidence --> finalize_trace;
	decide_next_action -. &nbsp;retry&nbsp; .-> apply_retry;
	decide_next_action -. &nbsp;insufficient_evidence&nbsp; .-> build_insufficient_evidence;
	decide_next_action -. &nbsp;generate&nbsp; .-> generate_answer;
	evaluate_context --> decide_next_action;
	generate_answer --> finalize_trace;
	initialize --> planner;
	planner --> strategy_select;
	retrieve --> evaluate_context;
	strategy_select --> retrieve;
	finalize_trace --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
